#!/usr/bin/env fish
helm repo add mojo2600 https://mojo2600.github.io/pihole-kubernetes/
helm repo update
kubectl create -f namespace.json
helm install -n pihole -f override.yaml pihole mojo2600/pihole
kubectl apply -n pihole -f ingress.yaml
